### ISSUE TITLE
Get strati column from an earth model

### ISSUE THREAD

**Issue by untereiner** [F2I-Consulting/fesapi#103]
**Is your feature request related to a problem? Please describe.**
I want to retrieve the stratigraphic column associated to an earth model interpretation

**Describe the solution you'd like**
Add a getter in the EarthModelInterpretation class

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by philippeVerney** [comment]
Thank you for the update.
FYI, this month is a fesapi initiative dedicated work month. You might wait for april for this to be implemented.

**Comment by untereiner** [comment]
ok but I can't wait. I'll do it in my fork in the meanwhile.

**Comment by philippeVerney** [comment]
I should be able to include that in my next PR (maximum end of this week) since it does not require a lot of changes.

**Comment by untereiner** [comment]
thank you!

**Comment by philippeVerney** [comment]
Look at this commit https://github.com/philippeVerney/fesapi/commit/58156cc17759918e335e0569141cef519e96d407 if you cannot wait at all (only earthModelInterp* files).
I won"t be able to test it regarding available time.
It will be part of next PR.
