### ISSUE TITLE
3D horizon 

### ISSUE THREAD

**Issue by shahzaib414** [F2I-Consulting/fesapi#105]
does fesapi provide support for 3D horizon Data

**Comment by philippeVerney** [comment]
Hi shahzaib414

Please follow these guidelines for contributions : https://github.com/F2I-Consulting/fesapi/blob/master/CONTRIBUTING.md

In your case, you should ask question using the forum not github : https://discourse.f2i-consulting.com/c/fesapi
And please, detail what is a "3D horizon Data". I personally can give several definitions for those terms.
