### ISSUE TITLE
compilation on macos

### ISSUE THREAD

**Issue by untereiner** [F2I-Consulting/fesapi#114]
# What are the steps to reproduce this issue?
macos compilation with gcc8-3

# What does happen?

> /Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.cpp:144:6: error: no declaration matches 'void common::HdfProxy::readArrayNdOfValues(const string&, void*, const hid_t&)'
 void HdfProxy::readArrayNdOfValues(const std::string & datasetName, void* values, const hid_t & datatype)
      ^~~~~~~~
In file included from /Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.cpp:19:
/Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.h:124:8: note: candidates are: 'void common::HdfProxy::readArrayNdOfValues(int, int, void*, long long unsigned int, const int&)'
   void readArrayNdOfValues(
        ^~~~~~~~~~~~~~~~~~~
/Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.h:81:8: note:                 'void common::HdfProxy::readArrayNdOfValues(const string&, void*, long long unsigned int*, long long unsigned int*, long long unsigned int*, long long unsigned int*, const unsigned int&, const int&)'
   void readArrayNdOfValues(
        ^~~~~~~~~~~~~~~~~~~
/Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.h:61:8: note:                 'void common::HdfProxy::readArrayNdOfValues(const string&, void*, long long unsigned int*, long long unsigned int*, const unsigned int&, const int&)'
   void readArrayNdOfValues(
        ^~~~~~~~~~~~~~~~~~~
/Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.h:49:8: note:                 'void common::HdfProxy::readArrayNdOfValues(const string&, void*, const int&)'
   void readArrayNdOfValues(const std::string & datasetName, void* values, const int & datatype);
        ^~~~~~~~~~~~~~~~~~~
In file included from /Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.cpp:19:
/Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.h:25:29: note: 'class common::HdfProxy' defined here
  class DLL_IMPORT_OR_EXPORT HdfProxy : public AbstractHdfProxy
                             ^~~~~~~~
/Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.cpp:162:6: error: no declaration matches 'void common::HdfProxy::readArrayNdOfValues(const string&, void*, long long unsigned int*, long long unsigned int*, const unsigned int&, const hid_t&)'
 void HdfProxy::readArrayNdOfValues(
      ^~~~~~~~
In file included from /Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.cpp:19:
/Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.h:124:8: note: candidates are: 'void common::HdfProxy::readArrayNdOfValues(int, int, void*, long long unsigned int, const int&)'
   void readArrayNdOfValues(
        ^~~~~~~~~~~~~~~~~~~
/Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.h:81:8: note:                 'void common::HdfProxy::readArrayNdOfValues(const string&, void*, long long unsigned int*, long long unsigned int*, long long unsigned int*, long long unsigned int*, const unsigned int&, const int&)'
   void readArrayNdOfValues(
        ^~~~~~~~~~~~~~~~~~~
/Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.h:61:8: note:                 'void common::HdfProxy::readArrayNdOfValues(const string&, void*, long long unsigned int*, long long unsigned int*, const unsigned int&, const int&)'
   void readArrayNdOfValues(
        ^~~~~~~~~~~~~~~~~~~
/Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.h:49:8: note:                 'void common::HdfProxy::readArrayNdOfValues(const string&, void*, const int&)'
   void readArrayNdOfValues(const std::string & datasetName, void* values, const int & datatype);
        ^~~~~~~~~~~~~~~~~~~
In file included from /Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.cpp:19:
/Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.h:25:29: note: 'class common::HdfProxy' defined here
  class DLL_IMPORT_OR_EXPORT HdfProxy : public AbstractHdfProxy
                             ^~~~~~~~
/Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.cpp:172:6: error: no declaration matches 'void common::HdfProxy::readArrayNdOfValues(const string&, void*, long long unsigned int*, long long unsigned int*, long long unsigned int*, long long unsigned int*, const unsigned int&, const hid_t&)'
 void HdfProxy::readArrayNdOfValues(
      ^~~~~~~~
In file included from /Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.cpp:19:
/Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.h:124:8: note: candidates are: 'void common::HdfProxy::readArrayNdOfValues(int, int, void*, long long unsigned int, const int&)'
   void readArrayNdOfValues(
        ^~~~~~~~~~~~~~~~~~~
/Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.h:81:8: note:                 'void common::HdfProxy::readArrayNdOfValues(const string&, void*, long long unsigned int*, long long unsigned int*, long long unsigned int*, long long unsigned int*, const unsigned int&, const int&)'
   void readArrayNdOfValues(
        ^~~~~~~~~~~~~~~~~~~
/Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.h:61:8: note:                 'void common::HdfProxy::readArrayNdOfValues(const string&, void*, long long unsigned int*, long long unsigned int*, const unsigned int&, const int&)'
   void readArrayNdOfValues(
        ^~~~~~~~~~~~~~~~~~~
/Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.h:49:8: note:                 'void common::HdfProxy::readArrayNdOfValues(const string&, void*, const int&)'
   void readArrayNdOfValues(const std::string & datasetName, void* values, const int & datatype);
        ^~~~~~~~~~~~~~~~~~~
In file included from /Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.cpp:19:
/Users/untereiner/Documents/Developments/cgogn2/fesapi-superbuild/fesapi/src/common/HdfProxy.h:25:29: note: 'class common::HdfProxy' defined here
  class DLL_IMPORT_OR_EXPORT HdfProxy : public AbstractHdfProxy

# What were you expecting to happen?
good compilation

# Any logs, error output, etc?
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

# Any other comments?
replace hid_t by int and replace datatype  by hid_t(datatype) 

# What versions of fesapi are you using?
master branch

**Comment by philippeVerney** [comment]
Hi Lionel,

Are you sure not that you are not building with HDF5 1.10.* instead of HDF5 1.8.* as stated in the [README](https://github.com/F2I-Consulting/fesapi)?

We have an already opened issue (limitation) looking that yours : #76

**Comment by untereiner** [comment]
Hi 
If I am not doing wrong I use https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.21/src/hdf5-1.8.21.tar.gz

**Comment by philippeVerney** [comment]
Line 54 of H5IPublic.h located in hdf5-1.8.21.tar.gz\hdf5-1.8.21.tar\hdf5-1.8.21\hdf5-1.8.21\src\ of you rlink above indicate : "typedef int hid_t;"

So using hid_t or int should be the same I guess. Maybe macos has a a macro defined somewhere which would change that.
Could you tell me the definition of your hid_t datatype please on your os? And the file where it is defined?

**Comment by untereiner** [comment]
I have the same as you: `typedef int hid_t;`
I had a very strange behavior. I compiled a second time and it works now.
