### ISSUE TITLE
Crash because getParentLocalPropertyKind() is nullptr

### ISSUE THREAD

**Issue by cgodkin** [F2I-Consulting/fesapi#117]
# What are the steps to reproduce this issue?

Start with example.cpp from latest GitHub master.  (This also happened with 0.14 so I updated today to make sure it hadn't been fixed already.)

Make three changes:
1. Modify deserialize() to use one of the overloads with the resource directory instead of the basic one.  
2. Modify main() to change filePath to "gullfaks_explicit.epc" (from upload/testingV2_0/paradigm/ilabMay2016/gullfaks_explicit.epc ; we have had this model as a test in our automated testing for a long time.)
3. Comment out the "if (serialize()) {" and the closing brace.

Build and run the program with VS 2015.

# What does happen?

Crash at line 107 of PropertyKind.cpp because getParentLocalPropertyKind() is nullptr.

# What were you expecting to happen?

A very long dump.  (The crash happens right away to me.)

# Any logs, error output, etc?

N/A unless it would be easier if I sent you my modified example.cpp

# Any other comments?

I hadn't updated from master since last September until I updated a couple of weeks ago.  Working with the version from September 10, this all worked fine.

Note that it works fine if you do not pass the resource directory.

I would normally try to debug this myself and provide a PR but I'm busy with another project at the moment.  (In a few days I may have time though.)  But if you know what to do right away...

# What versions of fesapi are you using?

0.15  (also happened with 0.14)

**Comment by cgodkin** [comment]
To clarify, I updated today a second time from GitHub master.  In other words, I updated to 0.14 and got the crash so I updated today and still see the problem.

**Comment by philippeVerney** [comment]
Hi Carl,

Thanks for the feedback.

The EPC file uses partial property kind which is very uncommon and which is badly supported in this fesapi version. But it is standard so Fesapi should not complain and should not crash.
I am going to fix that probably in my next PR coming in some few hours.

**Comment by philippeVerney** [comment]
The error occurred when some parent property kind were partial (not in the EPC document). It is now fixed : 
- the validation is now confirmed in such a case i.e. we assume that what we cannot validate is true by default.
- a warning is raised in such a case which can be get using EpcDocument::getWarnings()

**Comment by cgodkin** [comment]
Thanks a lot.  I updated again and the fix works here too of course.
