### ISSUE TITLE
Grid2dRepresentation ignores LocalCrs

### ISSUE THREAD

**Issue by mgimhof** [F2I-Consulting/fesapi#121]
# What are the steps to reproduce this issue?
	std::string filepath = "test.epc";
	auto pck = common::EpcDocument(filepath, common::EpcDocument::OVERWRITE);
	auto hdfProxy = pck.createHdfProxy("", "Hdf Proxy", pck.getStorageDirectory(), pck.getName() + ".h5");

	auto local3dCrs = pck.createLocalDepth3dCrs("", "Default local CRS", 1000.0, 2000.0, 3000.0, .0, gpq::eml20__LengthUom__m, 23031, gpq::eml20__LengthUom__m, "Unknown", false);
	auto horizon1 = pck.createHorizon("35d7b57e-e5ff-4062-95af-ba2d7c4ce347", "Horizon1");
	auto horizon1Interp1 = pck.createHorizonInterpretation(horizon1, "ac12dc12-4951-459b-b585-90f48aa88a5a", "Horizon1 Interp1");
	
	auto h1i1g2dRep = pck.createGrid2dRepresentation(horizon1Interp1, local3dCrs, "1b8f7b73-6e04-4b28-ac6f-ef6256c49258", "Horizon1 Interp1 Grid2dRep");
	double zValues[8] = { 300, 300, 350, 350, 300, 300, 350, 350 };
	h1i1g2dRep->setGeometryAsArray2dOfExplicitZ(zValues, 4, 2, hdfProxy, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 100.0, 0.0, 1.0, 0.0, 200.0);

	auto x = h1i1g2dRep->getXOriginInGlobalCrs();
	auto y = h1i1g2dRep->getYOriginInGlobalCrs();
	std::cout << x << " " << y << "\n";

# What does happen?
It looks like x is local 0.0 and y is local 0.0
Should have added (1000 2000) to xy

# What were you expecting to happen?
…

# Any logs, error output, etc?
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

# Any other comments?
…

# What versions of fesapi are you using?
0.15 up to #112

**Comment by mgimhof** [comment]
btw: the zvalues appear to lack the 3000 shift as well

**Comment by philippeVerney** [comment]
Thanks for the bug report and for the piece of code perfectly illustrating the problem.

It looks like an important bug. I will add unit test on that!

**Comment by cgodkin** [comment]
I just ran into this problem today.  Thanks a lot for fixing it before I found it! ;>)
