### ISSUE TITLE
unsigned int SealedSurfaceFrameworkRepresentation::getRepresentationINDEXOfContactPatch

### ISSUE THREAD

**Issue by mgimhof** [F2I-Consulting/fesapi#124]
when deserializing contacts in SealedSurfaceFrameworkRepresentation, I finally arrive at

resqml_wtf.getRepresentationOfContactPatch(contact_index, patch_index);

which returns a the supporting representation. Rather than getting the reference, I would like to get the representation index. 

RESQML2_NS::AbstractRepresentation* SealedSurfaceFrameworkRepresentation::getRepresentationIndexOfContactPatch(unsigned int crIndex, unsigned int cpIndex) const
{
	return getContactPatch(crIndex, cpIndex)->RepresentationIndex;
}

I have already deserialized this representation and put it into  vector whose index matches the representation index.

The workaround is to create a map between abstractrepresentation and index, but I would prefer to be able to continue work with the indices

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by philippeVerney** [comment]
Hi Matthias,

Agreed. I will provide theses functions (probably in addition to the existing ones).
