### ISSUE TITLE
StratigraphicColumnRankInterpretation.cpp does not require a fluid organization

### ISSUE THREAD

**Issue by mgimhof** [F2I-Consulting/fesapi#143]
Had me going for a while when I tried to understand the log output!

StratigraphicColumnRankInterpretation.cpp, line 40
throw invalid_argument("The kind of the organization feature is not a fluid organization.");

I think that should read a "The kind of the organization feature is not a stratigraphic model" or something like that. Took me a while to figure out what the log message was trying to tell me!

**Comment by philippeVerney** [comment]
Thanks Matthias.
It looks like a bad copy-paste on my side which has been integrated at commit 605a04d1cc3ae114e569703aa3b590486f1f0a6b.
Sorry about that.
