### ISSUE TITLE
get parametric ijk grid parameters between two kinterfaces

### ISSUE THREAD

**Issue by untereiner** [F2I-Consulting/fesapi#152]
**Is your feature request related to a problem? Please describe.**
I want to access to the parameters between two k interfaces of a parametric grid 

**Describe the solution you'd like**
A fonction similar to `getParametersOfNodes` but with two supplemental parameters 

**Describe alternatives you've considered**
do same thing in my code by getting the hdfproxy.

**Additional context**

**Comment by philippeVerney** [comment]
Just to be sure : do you really want parameters? 
Or is computed XYZ of the nodes ok with your request?

If computed XYZ of the nodes are ok with your request, it already exists in the super class AbstractIjkGridRepresentation. Look at all methods containing KInterface.

**Comment by untereiner** [comment]
Yes, I need the parameters not the computed xyz coordinates

**Comment by philippeVerney** [comment]
Thanks,
It looks to be just to extract line range 689-708 in a separate public method. I'll check that in next commit of possible.

**Comment by untereiner** [comment]
thanks!
