### ISSUE TITLE
Content type reading problem

### ISSUE THREAD

**Issue by untereiner** [F2I-Consulting/fesapi#154]
# What are the steps to reproduce this issue?
1. Open a file where the xml content type is `version=2.0.1`

# What does happen?

> The content type application/x-resqml+xml;version=2.0.1;type=obj_TriangulatedSetRepresentation could not be wrapped by fesapi. The related instance will be ignored.

# What were you expecting to happen?

loading the content type

# Any logs, error output, etc?
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

# Any other comments?

In the function DataObjectRepository::addOrReplaceGsoapProxy add `(contentType.find("application/x-resqml+xml;version=2.0.1;type=obj") != string::npos))`

# What versions of fesapi are you using?
1.0

**Comment by philippeVerney** [comment]
Thanks for the feedback.
It is true that 2.0.1 is no more supported. And it is by mistake!!!

However, TriangulatedSetRepresentation is a wrong example. TriangulatedSetRepresentation only belongs to 2.0 not to 2.0.1. If it is/was read, it was not intended.
2.0.1 are only : Activity, ActivityTemplate, PropertySeries (at least for now in Fesapi)

I'll fix that in next commit

**Comment by untereiner** [comment]
But what if the version is written as this in the epc I am working with for a TriangulatedSetRepresentation ?

**Comment by philippeVerney** [comment]
That is unfortunately for you not valid from the standard rules.

Below is the list of v2.0.1 objects in RESQML 2.0.1 (only 12 files and no TriangulatedSetRepresentation)

> Search "2.0.1" (12 hits in 12 files)
>   C:\Users\Philippe\dev\gsoapGeneration\energyml\data\resqmlv2\v2.0.1\xsd_schemas\Activities.xsd (1 hit)
> 	Line 2: <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:resqml="http://www.energistics.org/energyml/data/resqmlv2" xmlns:eml="http://www.energistics.org/energyml/data/commonv2" targetNamespace="http://www.energistics.org/energyml/data/resqmlv2" elementFormDefault="qualified" version="2.0.1">
>   C:\Users\Philippe\dev\gsoapGeneration\energyml\data\resqmlv2\v2.0.1\xsd_schemas\obj_Activity.xsd (1 hit)
> 	Line 2: <xsd:schema xmlns:resqml="http://www.energistics.org/energyml/data/resqmlv2" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:eml="http://www.energistics.org/energyml/data/commonv2" targetNamespace="http://www.energistics.org/energyml/data/resqmlv2" elementFormDefault="qualified" attributeFormDefault="unqualified" version="2.0.1">
>   C:\Users\Philippe\dev\gsoapGeneration\energyml\data\resqmlv2\v2.0.1\xsd_schemas\obj_ActivityTemplate.xsd (1 hit)
> 	Line 2: <xsd:schema xmlns:resqml="http://www.energistics.org/energyml/data/resqmlv2" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:eml="http://www.energistics.org/energyml/data/commonv2" targetNamespace="http://www.energistics.org/energyml/data/resqmlv2" elementFormDefault="qualified" attributeFormDefault="unqualified" version="2.0.1">
>   C:\Users\Philippe\dev\gsoapGeneration\energyml\data\resqmlv2\v2.0.1\xsd_schemas\obj_CategoricalPropertySeries.xsd (1 hit)
> 	Line 2: <xsd:schema xmlns:resqml="http://www.energistics.org/energyml/data/resqmlv2" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:eml="http://www.energistics.org/energyml/data/commonv2" targetNamespace="http://www.energistics.org/energyml/data/resqmlv2" elementFormDefault="qualified" attributeFormDefault="unqualified" version="2.0.1">
>   C:\Users\Philippe\dev\gsoapGeneration\energyml\data\resqmlv2\v2.0.1\xsd_schemas\obj_CommentPropertySeries.xsd (1 hit)
> 	Line 2: <xsd:schema xmlns:resqml="http://www.energistics.org/energyml/data/resqmlv2" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:eml="http://www.energistics.org/energyml/data/commonv2" targetNamespace="http://www.energistics.org/energyml/data/resqmlv2" elementFormDefault="qualified" attributeFormDefault="unqualified" version="2.0.1">
>   C:\Users\Philippe\dev\gsoapGeneration\energyml\data\resqmlv2\v2.0.1\xsd_schemas\obj_ContinuousPropertySeries.xsd (1 hit)
> 	Line 2: <xsd:schema xmlns:resqml="http://www.energistics.org/energyml/data/resqmlv2" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:eml="http://www.energistics.org/energyml/data/commonv2" targetNamespace="http://www.energistics.org/energyml/data/resqmlv2" elementFormDefault="qualified" attributeFormDefault="unqualified" version="2.0.1">
>   C:\Users\Philippe\dev\gsoapGeneration\energyml\data\resqmlv2\v2.0.1\xsd_schemas\obj_DiscretePropertySeries.xsd (1 hit)
> 	Line 2: <xsd:schema xmlns:resqml="http://www.energistics.org/energyml/data/resqmlv2" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:eml="http://www.energistics.org/energyml/data/commonv2" targetNamespace="http://www.energistics.org/energyml/data/resqmlv2" elementFormDefault="qualified" attributeFormDefault="unqualified" version="2.0.1">
>   C:\Users\Philippe\dev\gsoapGeneration\energyml\data\resqmlv2\v2.0.1\xsd_schemas\obj_StreamlinesFeature.xsd (1 hit)
> 	Line 2: <xsd:schema xmlns:resqml="http://www.energistics.org/energyml/data/resqmlv2" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:eml="http://www.energistics.org/energyml/data/commonv2" targetNamespace="http://www.energistics.org/energyml/data/resqmlv2" elementFormDefault="qualified" attributeFormDefault="unqualified" version="2.0.1">
>   C:\Users\Philippe\dev\gsoapGeneration\energyml\data\resqmlv2\v2.0.1\xsd_schemas\obj_StreamlinesRepresentation.xsd (1 hit)
> 	Line 2: <xsd:schema xmlns:resqml="http://www.energistics.org/energyml/data/resqmlv2" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:eml="http://www.energistics.org/energyml/data/commonv2" targetNamespace="http://www.energistics.org/energyml/data/resqmlv2" elementFormDefault="qualified" attributeFormDefault="unqualified" version="2.0.1">
>   C:\Users\Philippe\dev\gsoapGeneration\energyml\data\resqmlv2\v2.0.1\xsd_schemas\PropertySeries.xsd (1 hit)
> 	Line 2: <xs:schema targetNamespace="http://www.energistics.org/energyml/data/resqmlv2" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:resqml="http://www.energistics.org/energyml/data/resqmlv2" version="2.0.1" xmlns:eml="http://www.energistics.org/energyml/data/commonv2" elementFormDefault="qualified">
>   C:\Users\Philippe\dev\gsoapGeneration\energyml\data\resqmlv2\v2.0.1\xsd_schemas\ResqmlAllObjects.xsd (1 hit)
> 	Line 2: <xsd:schema xmlns:resqml="http://www.energistics.org/energyml/data/resqmlv2" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:eml="http://www.energistics.org/energyml/data/commonv2" targetNamespace="http://www.energistics.org/energyml/data/resqmlv2" elementFormDefault="qualified" attributeFormDefault="unqualified" version="2.0.1">
>   C:\Users\Philippe\dev\gsoapGeneration\energyml\data\resqmlv2\v2.0.1\xsd_schemas\Streamlines.xsd (1 hit)
> 	Line 2: <xs:schema targetNamespace="http://www.energistics.org/energyml/data/resqmlv2" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:resqml="http://www.energistics.org/energyml/data/resqmlv2" xmlns:eml="http://www.energistics.org/energyml/data/commonv2" version="2.0.1" elementFormDefault="qualified">

The reason is that 2.0.1 does not intend to create another "class/complex type" for RIGOROUSLY EXACT same class/complex type.
For example there is only one TriangulatedSetRepresentation : not a 2.0 one and a 2.0.1 one.

**Comment by philippeVerney** [comment]
http://docs.energistics.org/#EID/EID_TOPICS/EID-000-007-0-C-sv4000.html

> “version=” is the schema version of the object. If an object itself is versioned, this is NOT the version of the object; it is the version of the schema to which the object conforms.

The "lines 2" in my above message show exactly the version attribute of the schema of the only twelve 2.0.1 XSD files.

**Comment by untereiner** [comment]
I understand the standard thing but fesapi could read these data until now... It should allow some retro compatibility

**Comment by philippeVerney** [comment]
Sorry but I disagree.
Fesapi must honor the standard. That's the only intent of Fesapi.
Fesapi does not guarantee a retrocompatibility with itself. It only targets to guarantee a RESQML compatibility.

You can (very) easily change that in fesapi as it is open source.
You also can (very) easily fix your epc document before to call fesapi in your program (just edit the content type files in the epc).

If I open the door to read RESQML-like files, I will have to support so much details (probably at least one per software). I face this kind of problem too much and, to me, the only solution is that the exporters fix their code in order to conform to RESQML.

**Comment by philippeVerney** [comment]
If the problem occurs very often, I could think about just logging a warning.
As far as I know, I have never seen this problem before (2.0.1 instead of 2.0). Is it possible to know who is the exporter?
Is it a well known published software?

**Comment by untereiner** [comment]
it is a dataset from total. When I look into the epc file. The Content_Types.xml file contains this version for each entity:
`application/x-resqml+xml;version=2.0.1;type=obj_TriangulatedSetRepresentation`
But when I look into the xml file of this entity the header says  `schemaVersion="2.0"`

**Comment by philippeVerney** [comment]
It is probably a testing version because Total export is one which I know a lot and it does not export such epc document. Or it is an EPC modified version (using another tier software).
Total indeed uses Fesapi which does not export this kind of content type (as far as I know and as long I can check).

Please work on some non too old testing Total export.
For example, if you take the Total export on Energistics FTP : /upload/testingV2_0/total/alwynStep1 you would never see this kind of weird export on triangulated set representation.

**Comment by untereiner** [comment]
This version thing concerns every entity in the epc file... (IJKGridRepresentation, etc...)
Very strange behavior.
I have a another problem with EpcExternalPartReference that thows an exception

**Comment by philippeVerney** [comment]
I am really surprised that this file comes from Total to be honest (without third party modification). I have never had any issue with for years and as you know, I really know well Total exports. You can send me it be email if you want I study the origin.
About EpcExternalPartReference, I need more explanation but I would not be surprised about some bus on my side. Last commit is a huge one.

**Comment by untereiner** [comment]
I have to much trouble with the last commit. I rolled everything back and just picked out the function I needed `getParametersOfNodesOfKInterfaceSequenceOfPatch`

**Comment by philippeVerney** [comment]
@untereiner : 

> I have a another problem with EpcExternalPartReference that thows an exception

The PR #161 will probably fix your bug
