### ISSUE TITLE
KDirection computation

### ISSUE THREAD

**Issue by untereiner** [F2I-Consulting/fesapi#162]
It is a question. I do not know if it is a bug or a feature :)

# What are the steps to reproduce this issue?
Use the method setGeometryAsParametricSplittedPillarNodes on an ParametricGrid

# What does happen?
The KDirection is automatically computed using the control points.
The computation takes into account the control points of pillars that are not defined (with pillarKind == -1). In my case these pillars have an inverted z coordinate. It results to a 'not monotonic'. So, my input and output grids do not have the same KDirection even the output one is just a subset of the input one (by removing some k layers).

# What were you expecting to happen?
My grid should be in KDirection down state.

# Any logs, error output, etc?

# Any other comments?

# What versions of fesapi are you using?

**Comment by philippeVerney** [comment]
Thanks Lionel,

I think this is a Fesapi bug.
I'll look at it in next commit

**Comment by untereiner** [comment]
Is it possible to have computeKDirection as a public member function and a parameter of type gsoap_resqml2_0_1::resqml2__KDirection for the function setGeometryAsParametricSplittedPillarNodes ?

**Comment by philippeVerney** [comment]
I think yes to first question even if I don't really understand the need.
I think no to second question. I want to avoid some possible invalid situations even if it has a performance impact.

**Comment by untereiner** [comment]
The idea is to let the user decide between keeping the KDirection of another grid (avoid recomputing it) or compute it (using the function) at the a save stage. I understand that it could create invalid situations if not used correctly.

**Comment by philippeVerney** [comment]
Computing the K direction is in my opinion not time consuming even if huge grids regarding the other things to write. I think it is non significant regarding the global export of a grid.
So, I would prefer not even allow this optimization to be honest which could allow inconsistencies. I wuld even like to commute K Direction everytime longer term (but it is harder, more time consuming in non parametric case).
If I am wrong, i.e. if you observed some significant performance penalties, I could change my mind.
