### ISSUE TITLE
The documentation of setValuesOfFloatHdf5ArrayOfValues is misleading

### ISSUE THREAD

**Issue by psaglio** [F2I-Consulting/fesapi#184]
# What are the steps to reproduce this issue?
Just look at the documentation included into resqml2_0_1/ContinuousProperty.h:

/**
		* Create a 3d array of explicit float values to the property values. No values are written to this array yet then the HDF5 array contains uninitialized values.
		* @param valueCountInFastestDim	The number of values to write in the fastest dimension (mainly I dimension).
		* @param valueCountInMiddleDim	The number of values to write in the middle dimension (mainly J dimension).
		* @param valueCountInSlowestDim The number of values to write in the slowest dimension (mainly K dimension).
		* @param proxy					The HDF proxy where to write the property values. It must be already opened for writing and won't be closed in this method.
		*/
		DLL_IMPORT_OR_EXPORT void pushBackFloatHdf5ArrayOfValues(
			const ULONG64& valueCountInFastestDim,
			const ULONG64& valueCountInMiddleDim,
			const ULONG64& valueCountInSlowestDim,
			COMMON_NS::AbstractHdfProxy* proxy
		);

		/**
		* Set some values of an existing 3d array of explicit float values of a particular patch. This method makes use of HDF5 hyperslabbing.
		* This method is to be used along with createFloatHdf5ArrayOfValues.
		* @param values					All the property values to set ordered according the topology of the representation it is based on.
		* @param valueCountInFastestDim	The number of values to write in the fastest dimension (mainly I dimension).
		* @param valueCountInMiddleDim	The number of values to write in the middle dimension (mainly J dimension).
		* @param valueCountInSlowestDim The number of values to write in the slowest dimension (mainly K dimension).
		* @param offsetInFastestDim		The offset to write in the fastest dimension (mainly I dimension).
		* @param offsetInMiddleDim		The offset value to write in the middle dimension (mainly J dimension).
		* @param offsetInSlowestDim		The offset value to write in the slowest dimension (mainly K dimension).
		* @param proxy					The HDF proxy where to write the property values. It must be already opened for writing and won't be closed in this method.
		* @param patchIndex				The index of the patch we want to set some values. If not present, the last patch is arbitrarily taken into account.
		*/
		DLL_IMPORT_OR_EXPORT void setValuesOfFloatHdf5ArrayOfValues(

# What does happen?
The documentation of setValuesOfFloatHdf5ArrayOfValues refers to the "createFloatHdf5ArrayOfValues" function which does not exist.

# What were you expecting to happen?
I guess it should refer to "pushBackFloatHdf5ArrayOfValues" instead.

# Any logs, error output, etc?
N/A

# Any other comments?
No

# What versions of fesapi are you using?
0.16.0

**Comment by philippeVerney** [comment]
Thanks Philippe.
You are perfectly right.
I'll fix that this soon.

**Comment by psaglio** [comment]
Thanks Philippe. As you probably guessed I'm giving v 0.16.0 a try, as the version we use is getting rather old. I will let you know how it went.

**Comment by philippeVerney** [comment]
@psaglio FYI, I plan to release the 1.0.0.0 version beginning of november.
The main difference is about the decorrelation between the data source (EPC or another "store") and the in memory representation of the store objects (dataobject repository).
You may want to go directly to 1.0.0.0 which is in dev in the current master branch.
However, you could face much more issue since the changes are much bigger mainly cause of preparation for ETP in fesapi, next year probably (depending when the official ETP release will be operated by Energistics.

I have no particular advise. I just want to let you know.
