### ISSUE TITLE
Simply deserializing an EPC could create an Hdf5 file on disk in READ_WRITE mode

### ISSUE THREAD

**Issue by untereiner** [F2I-Consulting/fesapi#201]
# What are the steps to reproduce this issue?
1. call open() on an HdfProxy object with no hdf5 file pointed out

# What does happen?
create an empty h5 file

# What were you expecting to happen?
throw an exception ?
Maybe the H5Fis_hdf5 should be before the H5Fcreate for the READ_WRITE case

# Any logs, error output, etc?
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

# Any other comments?
…

# What versions of fesapi are you using?
linux

**Comment by philippeVerney** [comment]
Hi Lionel,

Could you explain "an HdfProxy object with no hdf5 file pointed out".
Is it when you do : DataObjectRepository::createHdfProxy(guid, "myTitle", "", "", DataObjectRepository::openingMode::OVERWRITE) ?

**Comment by untereiner** [comment]
Hi,
when the .h5 file has been moved and is not in the "saved" directory

**Comment by philippeVerney** [comment]
How can Fesapi dould know that?
If you do DataObjectRepository::createHdfProxy(guid, "myTitle", "myH5.h5", "/savedDirectory", DataObjectRepository::openingMode::OVERWRITE), I think it is normal that Fesapi creates the file if not found.
Are you proposing an enum like OVERWRITE_ONLY_IF PRESENT vs OVERWRITE_EVEN_IF_NOT_PRESENT. Or are you proposing that OVERWRITE implies that the file must exist? Then I will have to create an enum CREATE ?

**Comment by untereiner** [comment]
Sorry my comment is for READ_WRITE. OVERWRITE should write over the existing file...

**Comment by philippeVerney** [comment]
That's nearly the same, I think.
I understand that you want a different behavior between:
- create a file, open it and set read/write access
vs
- open an existing file in read/write access

Currently READ_WRITE do both. It creates if it does not exist.
This is what I understood now.

**Comment by untereiner** [comment]
Maybe I am misunderstanding something. How can I deal with an .h5 file which was moved and where his path no longer corresponds with the one in the EpcExternalPart ?

**Comment by philippeVerney** [comment]
Fesapi is indeed not good for that.
The only way I see for now would be first to try to open in READ mode in order to check its existency.

More generally speaking, Fesapi is really bad in READ-WRITE mode (not only from an H5 point of view). Fesapi has not been designed with the EPC as a persistent thing (i.e. a database). Fesapi, as it is recommended by the standard, consider the EPC as a transient file (life scope is the transfer time).

I am not telling I don't want to provide a solution but I just want to warn that Fesapi has not been designed with an EPC/H5 as a database in mind

**Comment by untereiner** [comment]
ok thanks for you answer

**Comment by untereiner** [comment]
I could try to write my own hdfProxy but how can I add it to fesapi such that the deserialization could create an instance of such a class ?

**Comment by philippeVerney** [comment]
As a short/middle term approach (workaround), this would be perfectly fine.

If you use master, then give a look at lines 403-407 of  fesapi/src/common/DataObjectRepository.cpp
If you use ETP branch (future), a factory pattern has been implemented, then give a look at lines 201-206 of  fesapi/src/common/EpcDocument.cpp

**Comment by philippeVerney** [comment]
Longer term, I think your potential developped hdfProxy would replace the current default one.
I agree with the problem you describe. It is just not a high priority at least for now and I cannot work on it now.

**Comment by untereiner** [comment]
I do not understand lines 403-407 in the master branch. Should I activate the macro WITH_EXPERIMENTAL ? I need to change the addOrReplaceGsoapProxy method to add a new template parameter in the "application/x-eml+xml;version=2.0;type=obj_" case ?

**Comment by philippeVerney** [comment]
> Should I activate the macro WITH_EXPERIMENTAL ?

No

> I need to change the addOrReplaceGsoapProxy method to add a new template parameter in the "application/x-eml+xml;version=2.0;type=obj_" case ?

Yes.
Change line 406 from
return addOrReplaceEpcExternalPartReference2_0<RESQML2_0_1_NS::HdfProxy>(xml);
to
return addOrReplaceEpcExternalPartReference2_0<MyNamespace::MyProxy>(xml);

**Comment by untereiner** [comment]
I was hoping a less invasive modification.. thanks for your time

**Comment by philippeVerney** [comment]
In the above PR, I just added an opening mode enumerated value READ_WRITE_DO_NOT_CREATE to support the desired behavior.
READ_WRITE still creates the file if not present.
