### ISSUE TITLE
Optional use of Cmake DEBUG Postfix to generate "d"-suffixed debug DLLs (windows)

### ISSUE THREAD

**Issue by pmuron** [F2I-Consulting/fesapi#205]
**Is your feature request related to a problem? Please describe.**
Manage uniformly debug DLL on windows (debug runtimes) where release/debug are co-located in same folder (e.g. same as boost install tree).

**Describe the solution you'd like**
Include DEBUG_POSTFIX "d" as target properties in CMake, make it optional if needs to be.

**Describe alternatives you've considered**
I basically hand-edit the CMake, it is admittedly not a big deal, more like a nice to have.

**Additional context**

**Comment by philippeVerney** [comment]
It looks totally fine with me.
No deadline, no priority but indeed on the todo list.
