### ISSUE TITLE
Support for PointsProperty

### ISSUE THREAD

**Issue by pmuron** [F2I-Consulting/fesapi#208]
**Is your feature request related to a problem? Please describe.**
One frequently needs to carry auxiliary geometrical information as properties. An simple example could be carrying pre-calculated center locations (for either cells center or adjacency centers) to perform some type of corner-point TRANSMISSIBILITY calculations.

**Describe the solution you'd like**
RESQML has provision for it through PointsProperty.

**Describe alternatives you've considered**
Use 2D ContinuousProperty is a possible workaround.

**Additional context**

**Comment by philippeVerney** [comment]
Agree.
