### ISSUE TITLE
Support for LocalCrs on AbstractProperty

### ISSUE THREAD

**Issue by pmuron** [F2I-Consulting/fesapi#209]
**Is your feature request related to a problem? Please describe.**
Use of property (Continuous or Points) to carry some additional geometrical information is frequent but it requires a local CRS for robustness.

**Describe the solution you'd like**
AbsractProperty has a LocalCrs attribute that could be exposed through FESAPI.

**Describe alternatives you've considered**
Default to local CRS attached to parent representation as fall-back mechanism when property is "detected" as being related to geometry (see other issue on why we need PointsProperty to make that inference).

**Additional context**

**Comment by pmuron** [comment]
See #208

**Comment by philippeVerney** [comment]
Agree.
