### ISSUE TITLE
ContinuousProperty::setValuesOfFloatHdf5ArrayOfValues resets the property's minimum and maximum values

### ISSUE THREAD

**Issue by psaglio** [F2I-Consulting/fesapi#215]
# What are the steps to reproduce this issue?
I use a combination of one call to pushBackFloatHdf5ArrayOfValues and many calls to setValuesOfFloatHdf5ArrayOfValues to iteratively fill a continuous property.

# What does happen?
The minimum and maximum values of the property get set to the minimum and maximum values of the last slab that was added (last call to setValuesOfFloatHdf5ArrayOfValues).

# What were you expecting to happen?
I would expect the minimum and maximum values to be set to the minimum and maximum values of the full set of slabs that were set rather than those of the last added one.

# Any logs, error output, etc?
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

# Any other comments?
I actually know the minimum and maximum values before starting to fill the property but could not find a way to assign them to the property.

# What versions of fesapi are you using?
0.16.0

**Comment by philippeVerney** [comment]
Thanks for reporting this bug Philippe. I confirm it and will fix it in 1.1.0.0. I hope you can cherry pick for 0.16 or adopt 1.1 which should be released beginning of march (or I will release a 0.16.1).

I disallow setting min and max in order for fesapi not to generate some potential invalid values. The cost in performance is certain... I am always doubtful on what is the right approach (how much flexible Fesapi should be...) but, for now, fesapi is more "validation" driven than performance driven.

**Comment by philippeVerney** [comment]
I see that Fesapi actually allows to set min and max values for the non slab setters. I will mimic this existing behavior.

**Comment by philippeVerney** [comment]
The PR is actually pretty big! It will probably be hard to cherry pick in 0.16.
I can provide a quick fix for 0.16.0 if needed as a diff file or as a 0.16.1 release.
Feel very free to ask if needed. You can reopen this ticket for that.
