### ISSUE TITLE
[Activity] no support for Array parameter (especially index of the parameter value in an array parameter)

### ISSUE THREAD

**Issue by untereiner** [F2I-Consulting/fesapi#224]
# What are the steps to reproduce this issue?
The function getParameterIndexOfTitle from the class Activity returns a vector of indices of the parameters indices but it not the indices stored in the parameter type.

# What does happen?
Can not know the exact order of the parameters since all parameters are not mandatory and thus the indices not contiguous 

# What were you expecting to happen?
The index of the parameter as written in the file.

# Any logs, error output, etc?
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

# Any other comments?
…

# What versions of fesapi are you using?
1.0.0.0

**Comment by philippeVerney** [comment]
Hi Lionel,

I am not sure to understand.
The function getParameterIndexOfTitle from the class Activity returns a vector of indices of the parameters which have the same title/name.
It does not return anything based on parameter type.

I do not understand why optionality matters here.

Example:
Activity UUID_A
0- param "myParam" value 26
1- param "myParam1" value 2
2- param "myParam10" value 5
3- param "myParam20" value 25
4- param "myParam1" value 26
5- param "myOptionalParam" value 45
X- param "myOtherOptionalParam" : it does not exist and consequently does not moidyf anythin in to the indexing.
 
If you would ask getParameterIndexOfTitle(myParam)
You should get {26} as a return value.
If you would ask getParameterIndexOfTitle(myParam1)
You should get {1, 4} as a return value.
etc...

**Comment by philippeVerney** [comment]
Edit of the example above.

**Comment by untereiner** [comment]
Example an activity following an activity template

ActivityTemplate
- Param title ObjA
- Param title ObjB
- Param title ObjC
- Param title icount
- Param title jcount
- Param title kcount
- Param title ObjR

Activity
- Param title ObjB ; Index 2
- Param title ObjC ; Index 3
- Param title jcount ; Index 5
- Param title ObjR ; Index 6

**Comment by philippeVerney** [comment]
The index you are talking about is optional. And it is only for **array** parameter.
Looking at your example, I also doubt you use it right. It looks you use it for, as you told, "the index of the parameter in the Activity Template" but this does not even exist in RESQML. The index of the parameter in the Activity Template is not needed because the parameters are organized by their title not their index/position.

This is not at all the same index FESAPI is dealing with. FESAPI is dealing with the index of the parameters in the XML document, not within the parameter array if the parameter is an array.
Support of array parameter is not supported yet. Your issue can be a feature request to support array parameter (but it would still not give exactly what I see in your example because I don't see any array parameter in your example).
Array parameters are definitely to be supported but I cannot give you any deadline for that.

**Comment by philippeVerney** [comment]
For completeness, here is the official doc stating that the index you are talking about is only for array parameter  : http://docs.energistics.org/#RESQML/RESQML_TOPICS/RESQML-500-290-0-R-sv2010.html

**Comment by untereiner** [comment]
thanks for the explanations! I will look at this activity thing again.

**Comment by untereiner** [comment]
Would it be possible to have a vector of the parameters of an Activity in the order they are stored in the xml file ?

**Comment by philippeVerney** [comment]
You can always have that by accessing the underlying gSoap proxy getGsoapProxy() and downcasting to the right type and then use gsoap accessors.

I doubt that FESAPI will one day provide such a return type. FESAPI granularity is arbitrarily at the level of the Energistics top level element. And a parameter is not such a top level element. This architectural choice is really debatable but today FESAPI follows this granularity level.

Endly, the current "index" is clearly done to achieve what you are describing (without vector usage).
You indeed have the count of parameters with Activity:: getParameterCount()
You can then loop from 0 to this count and "access to all the parameters independently of the name of the parameter" but dependently of the "order they are stored in the xml file".
For each iteration, you can use the methods: Activity::*****(const unsigned int & index) const = 0; for accessing details of each parameter such as the value, the title (and the Energsitics index in the future)

**Comment by untereiner** [comment]
I did what you suggested. The counter part is to manage the switch of the parameter type manually. Thank you
