### ISSUE TITLE
Minizip upstream version

### ISSUE THREAD

**Issue by adrien-jeser** [F2I-Consulting/fesapi#23]
# What are the steps to reproduce this issue?
When build the fesapi library.

# What does happen?
Build failed

# What were you expecting to happen?
Build with upstrream version

# Any logs, error output, etc?
https://ghostbin.com/paste/mokfy

# Any other comments?
None

# What versions of fesapi are you using?
Latest git version

---
Adrien Jeser
Software developer at Int France

**Comment by philippeVerney** [comment]
Hi Adrien,
Thanks for your issue.
The fesapi readme.md (root of the repository and shown at the github repo home page) indicates to use [this](https://github.com/F2I-Consulting/minizip) minizip version (in "Prepare the dependencies" chapter).

Is the purpose of your issue to no more use this version but another one? I presume it would probably be [this](https://github.com/nmoinvaz/minizip) minizip.

I think it would be better to use semi-official latest minizip from nmoinvaz but I have to run some tests before to integrate.
Some adopters also told me about [libarchive](https://github.com/libarchive/libarchive) which could be a good option. But it would need much more changes.

**Comment by adrien-jeser** [comment]
Hi Philippe,

I use the same minizip, provided by zlib , but the upstream version  http://www.winimage.com/zLibDll/minizip.html 

Many GNU/Linux distribution, use it.
Debian : https://packages.debian.org/stretch/libminizip-dev
Fedora : https://rpmfind.net/linux/RPM/fedora/devel/rawhide/i386/m/minizip-devel-1.2.11-4.fc27.i686.html
ArchLinux : https://www.archlinux.org/packages/core/x86_64/minizip/

--- 
Adrien Jeser
Software developer at Int France

**Comment by philippeVerney** [comment]
I remember having issues with this official minizip version. I think it was when trying to import minizip created archive with a pure windows unzipper library (it was a question of datetime of the archived files within the zip as far as I remember. It was years ago!!). That's why I shifted to a more recent minizip library. Indeed, I remember that rigorously speaking, minizip was incorrect. However, only this pure windows library checked this problem during unzipping.
However, I must say I did not study enough the problem. I'll look at it when I'll have time.

**Comment by philippeVerney** [comment]
Some more information to centralize all info.
Here was the problem I encountered with official minizip:

>Failure in reading using the MS OPC libraries.
>The failure occurred when I tried to enumerate the parts in the package.  The code showing the point of failure is below:
```
MultiByteToWideChar(CP_ACP, 0, opc_name_.c_str(), slength, buf, len);
if (SUCCEEDED(md_->hr)) { md_->hr = LoadPackage(md_->opcFactory, buf, &md_->opcPackage);  if (!SUCCEEDED(md_->hr)) fm = "Load Fail"; }
if (SUCCEEDED(md_->hr)) { md_->hr = md_->opcPackage->GetPartSet(&md_->packagePartSet);  if (!SUCCEEDED(md_->hr)) fm = "GetPartSet Fail"; }
if (SUCCEEDED(md_->hr)) { md_->hr = md_->opcPackage->GetRelationshipSet(&md_->packageRelationshipSet);  if (!SUCCEEDED(md_->hr)) fm = "GetRelationshipSet Fail"; }
if (SUCCEEDED(md_->hr)) { md_->hr =  md_->packagePartSet->GetEnumerator(&partEnumerator);  if (!SUCCEEDED(md_->hr)) fm = "GetEnumerator Fail"; }
```
> The call to packagePartSet->GetEnumerator failed.
> A bit more information, the error code returned from the call to packagePartSet->GetEnumerator is: OPC_E_ZIP_INCONSISTENT_FILEITEM
> 0x80511005
> The file attributes recorded in a file header in the central directory are inconsistent with the attributes of the zipped file item.
> The zip headers all contains an invalid file modified date, reported as 'file last modified on (0x00000020 0x00000000):  1980-01-00 00:00:00', which doesn't match the modified date on the file entry.
> It may be that the MS OPC is tripping on this error, although it doesn't seem to bother winzip at all.

No more error after I shift to the current minizip library I am using (at least with MS OPC libraries) using Zip32.
Using Zip64, MS OPC libraries still complain:
> The zip64 bit files fail with the OPC_E_ZIP_INCONSISTENT_FILEITEM error code, “The file attributes recorded in a file header in the central directory are inconsistent with the attributes of the zipped file item”
> The zip64 files don’t flag any validation error on my winzip (winzip 14), but when I look at the contents of the test there is a possible inconsistency.
> The zip directory appears to contain: “unzip software version needed to extract (20):  2.0”
> While the entries contain: “unzip software version needed to extract (45):  4.5”
> The Microsoft API doesn’t provide enough detail on specifics of the detected inconsistency to be sure so this may or may not be the problem.

**Comment by philippeVerney** [comment]
Studying pro and cons, I agree that adopting the minizip upstream version looks to have more pros.
There is no perfect solution. Indeed, the minizip upstream version has shown some errors (maybe cause of usage and not cause of the library).
However, keeping an unofficial version of minizip look to have even more problem (mainly legal, maintainance and adoption).

By default, the minizip upstream version will be used and the current minizip version will be kept in a separate repository if someone wants to keep it.
