### ISSUE TITLE
Bad initialization of cumulativeLength->NullValue line 1454 of IjkGridParametricRepresentation.cpp

### ISSUE THREAD

**Issue by mpoudret** [F2I-Consulting/fesapi#25]
Hello,

I found an issue in IjkGridParametricRepresentation.cpp. Line 1454, cumulativeLength->NullValue is not properly instantiated. 

Regards,
Mathieu

# What are the steps to reproduce this issue?
1. calling setGeometryAsParametricSplittedPillarNodesUsingExistingDatasets method with splitCoordinateLineColumnCumulativeCount (which is actually and HDF5 dataset path within this method) lenght lesser than splitCoordinateLineCount - 1

# What does happen?
Out of range error occurs line 1454 of IjkGridParametricRepresentation.cpp

# What were you expecting to happen?
I think that line 1454 is inconsistent considering that within setGeometryAsParametricSplittedPillarNodesUsingExistingDatasets, splitCoordinateLineColumnCumulativeCount parameter is an HDF5 dataset path. On my mind, the expression "splitCoordinateLineCount - 1" into brackets does not make sense. I think that this expression is a remain of the splitCoordinateLineColumnCumulativeCount unsigned int array.

# What versions of fesapi are you using?
fesapi is up to date according to december 11 2017 commit.

**Comment by philippeVerney** [comment]
Nice catch Mathieu!! You are fully right!
Thanks also for your related PR.
