### ISSUE TITLE
Provide broken-down FESAPI version as numbers

### ISSUE THREAD

**Issue by cgodkin** [F2I-Consulting/fesapi#304]
**Is your feature request related to a problem? Please describe.**
When upgrading from FESAPI 2.2 to FESAPI 2.3, I had to make some code changes.  It would have been useful to be able to have my code conditionally build for either version.  However, as far as I can see, the only FESAPI version is a string.

**Describe the solution you'd like**
I would suggest that the FESAPI version string be built up from numbers so the C preprocessor could do comparisons.  Something like
```
#define FESAPI_MAJOR_VERSION 2
#define FESAPI_MINOR_VERSION 3
#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)
#define FESAPI_VERSION STR(FESAPI_MAJOR_VER) STR(FESAPI_MINOR_VER) 
```

**Describe alternatives you've considered**
I don't think there's a way to do comparisons with strings in the C preprprocessor.

**Additional context**
I am not too clever about using the C preprocessor so I got the syntax above from [here](https://stackoverflow.com/a/5459929/2020178).

**Comment by philippeVerney** [comment]
For extra information:
- I decided to stringify the FESAPI version using CMAKE instead of the C preprocessor. I don't really like the C preprocessor indirection.
- If one wants to stringify a macro, gsoap provides such a functionality (same as described above) => SOAP_XSTRINGIFY in stdsoap2.h
