### ISSUE TITLE
Add functions to write unsigned types in properties

### ISSUE THREAD

**Issue by untereiner** [F2I-Consulting/fesapi#312]
**Is your feature request related to a problem? Please describe.**
Lack of functions to write unsigned types in properties

**Describe the solution you'd like**
Add shortcut functions setValuesOf**XXX**Hdf5Array**Y**dOfValues() in `AbstractValuesProperty` for missing types (i.e. mostly unsigned int 16,32,64) based on setValuesOf**XXX**Hdf5ArrayOfValues()

**Describe alternatives you've considered**
n.a.

**Additional context**
n.a.

**Comment by ddevienne** [comment]
ETP (Avro) does not support unsigned types. So what to do? Upscale to larger type? Always or depending on actual values?
Or play with the logical vs physical types I had them add to the ETP spec?  But then how portable is that?
What are you trying to achieve with this enhancement request?

**Comment by philippeVerney** [comment]
This topic is about FESAPI, not FETPAPI. AVRO (and ETP) is not in scope here.
HDF5 supports unsigned types and HDF5 is clearly in scope of FESAPI.
Some (non ETP aware) applications which are EPC/RESQML aware make use of unsigned types. RESQML (ETP is not of scope here) is definitely done to support unsigned types.

Final developer decide wether or not to use them or not depending on their usage context.

**Comment by ddevienne** [comment]
I see. Up to ETP-aware software to deal with it. Come to think of it, I actually do, since I've come across EPCs with unsigned integer arrays in fact. Nevermind then :). Thanks, --DD

**Comment by untereiner** [comment]
But I agree with you @ddevienne. It becomes touchy when these unsigned types come into the play with ETP. Personally I don't think the existing solution is the smoothed.
