### ISSUE TITLE
Compilation issue with aggressive warnings

### ISSUE THREAD

**Issue by untereiner** [F2I-Consulting/fesapi#324]
# What are the steps to reproduce this issue?
Compile using the -W-unused-parameter warning fails to compile. I know it is cosmetics...

# What does happen?
Issue with DataObjectRepository.h

# What were you expecting to happen?
no error

# Any logs, error output, etc?
A possible patch

```patch
--- src/common/DataObjectRepository.h	2023-07-24 17:46:49.000000000 +0200
+++ src/common/DataObjectRepository.h.patch	2023-07-24 21:35:30.775018191 +0200
@@ -758,7 +758,7 @@
 		 * @returns	A pointer to the new EPC external part reference.
 		 */
 		template <class NumericalValueBase>
-		NumericalValueBase* createEpcExternalPartReference(const std::string & guid, const std::string & title)
+		NumericalValueBase* createEpcExternalPartReference(const std::string & guid, const std::string & )
 		{
 			NumericalValueBase* result = new NumericalValueBase(getGsoapContext(), guid);
 			addDataObject(result);

```

# Any other comments?
n.a.

# What versions of fesapi are you using?
master

**Comment by philippeVerney** [comment]
Hi @untereiner 

I am afraid that this method has no more sens at all.
I am going to double check but your "cosmetic" remark might be a more important one allowing me delete a no sens method in FESAPI!

Thanks
