### ISSUE TITLE
Couldn't import fesapi after installation on Windows for Python

### ISSUE THREAD

**Issue by fuyuli123456** [F2I-Consulting/fesapi#325]
I believe I followed all the instructions except "Please first install the wheel located in fesapi/python/dist". There is no dist folder. Below are the files in the fesapi/python/ folder. Is the installation incomplete?

![image](https://github.com/F2I-Consulting/fesapi/assets/132941593/84b3fd2c-90ca-4cf4-b199-cb5558a72599)

**Comment by fuyuli123456** [comment]
I tried to add in python path: "sys.path.append("...\\fesapi\\python")", then "import fesapi", but got the error: cannot import name '_fesapi' from partially initialized module 'fesapi' (most likely due to a circular import) (...\python\fesapi\__init__.py)

**Comment by philippeVerney** [comment]
Hi,

Did you build FESAPI with visual studio and **install** it (by building the VIsual Studio INSTALL project)  ?
Could you paste last lines of the build log please?
This is the responsability of the (Visual studio) build to produce the fesapi/python/dist.
I'll give a try if you actually successfully did the build and the install.

**Comment by philippeVerney** [comment]
FYI if you understand cmake [this ](https://github.com/F2I-Consulting/fesapi/blob/79babc0c0ff97ce51496f260a5cf133990957398/src/CMakeLists.txt#L412) is where the final python generation should be processed.

**Comment by philippeVerney** [comment]
And [here](https://github.com/F2I-Consulting/fesapi/blob/79babc0c0ff97ce51496f260a5cf133990957398/.github/workflows/github-actions.yml#L138) is the CI where python is tested. However, it is done on ubuntu (not on windows).
I jsut highlighted the line of the install

**Comment by fuyuli123456** [comment]
Thank you for the quick reply and you are right. I previously built the entire Fesapi solution, and it turned out that the 3 other projects were built successfully, but the INSTALL project was skipped. I just re-built the INSTALL project and got the error below:
![image](https://github.com/F2I-Consulting/fesapi/assets/132941593/a4254593-ba93-4f1f-a0d3-9d3559ffe985)

**Comment by philippeVerney** [comment]
Try to rebuild in release (withdebinfo if you want and even without optimisation if you want) mode please.
It looks you build in debug mode which is much less tested.

**Comment by philippeVerney** [comment]
If you really want to build a debug version, please try first to set [this SWIG_LINKED_TO_RELEASE cmake variable](https://github.com/F2I-Consulting/fesapi/blob/79babc0c0ff97ce51496f260a5cf133990957398/python/CMakeLists.txt#L6)  to false.

**Comment by fuyuli123456** [comment]
I rebuilt with release mode and still got the same error:
![image](https://github.com/F2I-Consulting/fesapi/assets/132941593/6b8a1e35-733f-4aea-9efa-9437539fa91d)

**Comment by fuyuli123456** [comment]
The complete line before the error is below. And I can find the file "FesapiCppd.2.8.0.0.lib" under \fesapiEnv\build\install\lib\ and \fesapiEnv\build\src\Release\

>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:/Users/fuyl/tools/fesapiEnv/build/install/lib /LIBPATH:C:\ProgramData\Miniconda3\libs /LIBPATH:C:\ProgramData\Miniconda3\PCbuild\amd64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\lib\x64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\atlmfc\lib\x64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\VS\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\VS\UnitTest\lib /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 FesapiCppd.2.8.0.0.lib /EXPORT:PyInit__fesapi build\temp.win-amd64-3.9\Release\swigGeneratedPythonWrapper.obj /OUT:build\lib.win-amd64-3.9\fesapi\_fesapi.cp39-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.9\Release\_fesapi.cp39-win_amd64.lib
>LINK : fatal error LNK1181: cannot open input file 'FesapiCppd.2.8.0.0.lib'

**Comment by philippeVerney** [comment]
Hi @fuyuli123456 

I don't understand how you can have this error message if you have not played with the SWIG_LINKED_TO_RELEASE cmake variable.
The last line of your pasted log reference 'FesapiCppd.2.8.0.0.lib' which is the debug version (cause of the suffix 'd'). However, in your screenshot above, we can see at the first line that you copy the correct release library.... I guess your build environment is somehow in a dirty shape.
I tried myself on my own computer and cannot reproduce your error using v2.8.0.0. However, I have another error about an unresolved external symbol witsml2_1::Channel::setPropertyKind which is a regression starting from v2.7.0.0. I am just trying to fix it in my dev branch (i.e. for v2.9.0.0).

Either you can fix it yourself in your local v2.8.0.0 by adding a dllexport prefix as in [this commit file Channel.h](https://github.com/F2I-Consulting/fesapi/commit/d51f1dc6a9f189a52ade718e8fee0e618faacf97#diff-9d5b5f40e4487270b5bc88fa62f258d2d4528c0ef29c8950962f6b800a95f449)
Or you can build [v2.6.0.0](https://github.com/F2I-Consulting/fesapi/tree/v2.6.0.0) (Release mode)
Or you can build the [branch dev](https://github.com/F2I-Consulting/fesapi/tree/dev) (Release mode)
Or you can use the [wheel](https://github.com/F2I-Consulting/fesapi/releases/download/v2.6.0.0/fesapi-2.6.0.0-cp310-cp310-win_amd64.whl) I just produced for v2.6.0.0 and which I have put in [the v2.6.0.0 release assets](https://github.com/F2I-Consulting/fesapi/releases/tag/v2.6.0.0).

**Comment by fuyuli123456** [comment]
Thank you so much! I tried the wheel file. I couldn't get it work because I was not able to install python 3.10 on my computer. I have python 3.9.5 and 3.11.5 instead. Do you happen to have the wheel files for either of these two versions? If wheel can't work out, I will start over to build v2.6.0.0.

**Comment by philippeVerney** [comment]
OK, I just upgraded my python to v3.11.5 and relaunch the VS INSTALL project built.
Here is the result in the assets of v2.6.0.0 : https://github.com/F2I-Consulting/fesapi/releases/download/v2.6.0.0/fesapi-2.6.0.0-cp311-cp311-win_amd64.whl

**Comment by fuyuli123456** [comment]
this worked! Thank you so so much!!!
