### ISSUE TITLE
fesapi fails to find HDF5 version if hdf5 is built in Release mode using CMake on Centos-7

### ISSUE THREAD

**Issue by Algiane** [F2I-Consulting/fesapi#326]
# What are the steps to reproduce this issue?
1. Build hdf5 1.12 with cmake using `CMAKE_BUILD_TYPE=Release` cmake mode and a local `CMAKE_INSTALL_PREFIX=<HDF5_PREFIX>` on Centos-7
2. build and install hdf5
3. configure fesapi with `CMAKE_PREFIX_PATH=<HDF5_PREFIX>`

# What does happen?
Fesapi cannot find the correct `HDF5_VERSION`. This is induced by the fact that specifying an HDF5 version in the `find_package` command restricts to finding the hdf5_major.hdf5_minor versions exactly (dependent on the policy declared in the hdf5 cmake configuration files) whereas it should be interpreted as a minimal compatible version.

Consequently, the `COMMENT_HDF5_1_8` and `COMMENT_HDF5_1_10` CMake variable are erroneously defined leading to compilation errors.

Remarks:
  - I have no issue on Ubuntu
  - the cmake build type of hdf5 seems to affect the setting of the HDF5_VERSION variable and I have no issue with a Debug build and install of hdf5
 
# What were you expecting to happen?
A suitable detection of the hdf5 version.

# Any logs, error output, etc?
A suggestion to fix this:

Accept any version of hdf5 in FIND_PACKAGE(hdf5) and check the hdf5 version outside with `VERSION_LESS` CMake keyword:
```CMake
        FIND_PACKAGE(HDF5 REQUIRED COMPONENTS C)
        IF(HDF5_VERSION VERSION_LESS 1.8.18)
          MESSAGE(FATAL_ERROR "Wrong HDF5_VERSION=${HDF5_VERSION}")
        ENDIF()
```        

# Any other comments?
…

# What versions of fesapi are you using?
2.4.0.0

Thanks by advance for your help

**Comment by philippeVerney** [comment]
Hi @Algiane 

Just a quick check before to dive into this bug.
Does this help? https://github.com/F2I-Consulting/fesapi/issues/323#issuecomment-1713434882

**Comment by Algiane** [comment]
Hi @philippeVerney,

Thank you for your prompt answer:

  - I have a `cmake` subdir in `<HDF5_PREFIX>/share`
  - I use a classic installation of hdf5:
  ```bash
  cmake -DCMAKE_BUILD_TYPE=Release ..
  make
  make install
  ```

By the way: I can use the `WITH_LOCAL_HDF5` option of fesapi as a work around but I would prefer a more robust solution.

Best,

**Comment by philippeVerney** [comment]
Just for me to reproduce the problem when I'll find time, can I have the cmake version you use for the builds please?

Your suggested fix looks straigthforward and nice but I would like to try to understand better the bug first. If possible, I would ideally like to rely on what I understand from the official cmake FindHDF5 which indicates that, as you explained, 1.8.18 should be "interpreted as a minimal compatible version".
I'll have to especially read and understand more about your parenthesis : "dependent on the policy declared in the hdf5 cmake configuration files". Maybe you can give some particular hints about this file in your context if I want to reproduce the problem on my own centos7.

**Comment by Algiane** [comment]
Hi,

I use cmake version 3.24.3.

Regarding the question about the policy I will let @tbeltzun answer: we searched to understand the issue with the FindPackage command together and he is the one mastering CMake.

Best,

**Comment by philippeVerney** [comment]
It is an amazing comment @tbeltzun : thorough, really clear and with quotes and references!!! In one word, perfect!

Thanks a lot. I will definitely take into account this issue in next release!
