### ISSUE TITLE
Attribute ProjectedAxisOrder of AbstractLocal3dCrs cannot be set with fesapi

### ISSUE THREAD

**Issue by mpoudret** [F2I-Consulting/fesapi#33]
Hi,

Here is an issue regarding AbstractLocal3dCrs.

Regards,
Mathieu

# What are the steps to reproduce this issue?
Not relevant.

# What does happen?
Attribute ProjectedAxisOrder of class AbstractLocal3dCrs cannot be set with fesapi. There exists no appropriate setter or constructor.

# What were you expecting to happen?
To provide some facilities to set this attribute (probably by adding a parameter within constructors of classes LocalDepth3dCrs and LocalTime3dCrs).

# Any logs, error output, etc?
No.

# Any other comments?
No.

# What versions of fesapi are you using?
Up to date regarding last commit.

**Comment by philippeVerney** [comment]
Thanks for this issue.
Also, this attribute is not set in the various constructors.
