### ISSUE TITLE
Incorrect reading of the overall seismic support information when some of the patches have no support

### ISSUE THREAD

**Issue by psaglio** [F2I-Consulting/fesapi#43]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

# What are the steps to reproduce this issue?
Read a fault that have some patches with seismic support and others without seismic support.

# What does happen?
AbstractRepresentation::getSeismicSupportOfPatch(patch_index) may return wrong information for some patch_index (a different support than the one expected, or some support for patches that are not supposed to have one).

# What were you expecting to happen?
I expect getSeismicSupportOfPatch() to return the support defined in the EPC file for a patch, or nullptr when there is no support.

# Any logs, error output, etc?

# Any other comments?
In general I think pushBackSeismicSupport() would need to take the patch index as a parameter to correctly fill the seismicSupportSet vector.

# What versions of fesapi are you using?
An old one, but the issue exists in the latest source code available here.

**Comment by philippeVerney** [comment]
Hi Philippe,

Thanks a lot for reporting this bug.
I confirm it and I am working on it. FYI, I plan to remove the seismicSupportSet vector. getSeismicSupportOfPatch method would resolve the link on the fly which should prevent any error.

Regards

**Comment by psaglio** [comment]
Good, thanks Philippe.
