### ISSUE TITLE
range error

### ISSUE THREAD

**Issue by untereiner** [F2I-Consulting/fesapi#88]
# What are the steps to reproduce this issue?
1. look at AbstractIjkGridRepresentation::isColumnEdgeSplitted() function

# What does happen?
range error
```
if (edge > 7)
	throw range_error("Edge is out of range.");
```

# What were you expecting to happen?
I am expecting that edge must be < 4 as stated in function documentation

# Any logs, error output, etc?
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

# Any other comments?

# What versions of fesapi are you using?
master branch

**Comment by philippeVerney** [comment]
Thanks Lionel.
You are definitely right. I am going to fix it.
