### ISSUE TITLE
Provide better (more complete) java example

### ISSUE THREAD

**Issue by shahzaib414** [F2I-Consulting/fesapi#89]
i am facing error while creating .h5 file " The HDF5 file  does not exist or is not a valid HDF5 file ".  I am trying to write horizon in Java. But in cpp i am able to do this.

**Comment by philippeVerney** [comment]
Hi @shahzaib414,

Fesapi java version is tested and known to work (including horizon) with the various releases.
You should give an eye (debug) to file src/common/HdfProxy.cpp where the message is raised (about line 52 and 71).

Regards

**Comment by shahzaib414** [comment]
hy @philippeVerney  thanks for your response, but can you share some example how we can use Fesapi  to create horizon etc ? the one i tried with reference of native fesapi code example. That's the reason may be i am not doing it right . it will be really great if you share some example of fesapi java version or any document

**Comment by philippeVerney** [comment]
I cannot put that as a high priority but I let this issue opened in order to:
- encourage community to provide such examples.
- provide such examples if I have time.

**Comment by shahzaib414** [comment]
Thanks ,

**Comment by philippeVerney** [comment]
More complete example is provided in #92 in https://github.com/F2I-Consulting/fesapi/blob/master/cmake/FesapiJavaExample.java which will move to https://github.com/F2I-Consulting/fesapi/tree/master/java/example when operating CMake
